### PR TITLE
Carousel -> future

### PR DESCRIPTION
**Pull request by nfriedly**
This is a clone of #45 targeted at the branch `future`

I had to handle one merge conflict around line 1183 where it adds the insta-moderation links, so please give that a little extra scrutiny.

If you hide whitespace changes, it becomes a little more apparent what I actually did: https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/pull/46/files?utf8=%E2%9C%93&diff=split&w=1

### CODE REVIEW

**Comment by nfriedly** [comment]
I'm thinking that I'm going to change the behavior of `upload_media()` to return some metada instead of HTML. I'll probably move the html snippet generation to a new method and call that from `pic_loop()` with the metadata.

My reasoning, besides feeling a bit cleaner, is that this will enable a bit more flexibility with what data is passed to the templates and/or stored in the post metadata. In particular, I want an array of objects for the carousel, where each object includes all of the attachment ids (standard and low-rez video, screenshot, thumbnail, etc.)

Any thoughts?

**Comment by jtsternberg** [comment]
Regarding this PR, first I have to apologize because I told you to branch of the future branch to make your changes, but didn't realize I hadn't pushed my recent changes, which are the ones wich introduced the carousel feature. Can you please pull down a fresh copy of `future` and do some testing to see what of your PR still needs to be added?

**Comment by nfriedly** [comment]
Aah, that makes sense. No worries though.

I'm out on a work trip right now, so it'll probably a week or so, but I'll pull in the latest changes and see what's still needed.

**Comment by jtsternberg** [comment]
Closing this per https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/pull/45#issuecomment-431079650

**Pull request closed without merging**
